eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8765
  tomcat:
    max-threads: 50
spring:
  application:
    name: service-order-feign
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
feign:
   hystrix:
     enabled: true
