spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri:  https://gitee.com/itmayi      #https://github.com/MrYangPan/JavaIntegrate
          search-paths: respo
          default-label: master
          username:
          password:
server:
  port: 8889
